# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Game.find_or_create_by(name: 'Pokemon Spellcheck')
Game.find_or_create_by(name: 'Simple Math')
Game.find_or_create_by(name: 'Trivia')

TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of France?', correct_answer: 'Paris', incorrect_answers: ['London', 'Berlin', 'Madrid'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Germany?', correct_answer: 'Berlin', incorrect_answers: ['London', 'Paris', 'Madrid'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Spain?', correct_answer: 'Madrid', incorrect_answers: ['London', 'Paris', 'Berlin'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of England?', correct_answer: 'London', incorrect_answers: ['Paris', 'Berlin', 'Madrid'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Italy?', correct_answer: 'Rome', incorrect_answers: ['London', 'Paris', 'Madrid'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of the United States?', correct_answer: 'Washington D.C.', incorrect_answers: ['New York', 'Los Angeles', 'Chicago'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Canada?', correct_answer: 'Ottawa', incorrect_answers: ['Toronto', 'Vancouver', 'Montreal'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Mexico?', correct_answer: 'Mexico City', incorrect_answers: ['Guadalajara', 'Monterrey', 'Puebla'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Brazil?', correct_answer: 'Brasília', incorrect_answers: ['Rio de Janeiro', 'São Paulo', 'Salvador'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Argentina?', correct_answer: 'Buenos Aires', incorrect_answers: ['Córdoba', 'Rosario', 'Mendoza'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Australia?', correct_answer: 'Canberra', incorrect_answers: ['Sydney', 'Melbourne', 'Brisbane'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Japan?', correct_answer: 'Tokyo', incorrect_answers: ['Osaka', 'Yokohama', 'Nagoya'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of China?', correct_answer: 'Beijing', incorrect_answers: ['Shanghai', 'Guangzhou', 'Shenzhen'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of India?', correct_answer: 'New Delhi', incorrect_answers: ['Mumbai', 'Bangalore', 'Hyderabad'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of South Africa?', correct_answer: 'Pretoria', incorrect_answers: ['Cape Town', 'Johannesburg', 'Durban'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Egypt?', correct_answer: 'Cairo', incorrect_answers: ['Alexandria', 'Giza', 'Shubra El-Kheima'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Russia?', correct_answer: 'Moscow', incorrect_answers: ['Saint Petersburg', 'Novosibirsk', 'Yekaterinburg'])

TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Illinois?', correct_answer: 'Springfield', incorrect_answers: ['Chicago', 'Peoria', 'Rockford'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of California?', correct_answer: 'Sacramento', incorrect_answers: ['Los Angeles', 'San Francisco', 'San Diego'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of New York?', correct_answer: 'Albany', incorrect_answers: ['New York City', 'Buffalo', 'Rochester'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Texas?', correct_answer: 'Austin', incorrect_answers: ['Houston', 'Dallas', 'San Antonio'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Florida?', correct_answer: 'Tallahassee', incorrect_answers: ['Miami', 'Orlando', 'Tampa'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Ohio?', correct_answer: 'Columbus', incorrect_answers: ['Cleveland', 'Cincinnati', 'Toledo'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Pennsylvania?', correct_answer: 'Harrisburg', incorrect_answers: ['Philadelphia', 'Pittsburgh', 'Allentown'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Michigan?', correct_answer: 'Lansing', incorrect_answers: ['Detroit', 'Grand Rapids', 'Warren'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of New Jersey?', correct_answer: 'Trenton', incorrect_answers: ['Newark', 'Jersey City', 'Paterson'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Georgia?', correct_answer: 'Atlanta', incorrect_answers: ['Augusta', 'Columbus', 'Savannah'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of North Carolina?', correct_answer: 'Raleigh', incorrect_answers: ['Charlotte', 'Greensboro', 'Durham'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Virginia?', correct_answer: 'Richmond', incorrect_answers: ['Virginia Beach', 'Norfolk', 'Chesapeake'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Massachusetts?', correct_answer: 'Boston', incorrect_answers: ['Worcester', 'Springfield', 'Lowell'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Maryland?', correct_answer: 'Annapolis', incorrect_answers: ['Baltimore', 'Frederick', 'Rockville'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Wisconsin?', correct_answer: 'Madison', incorrect_answers: ['Milwaukee', 'Green Bay', 'Kenosha'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Minnesota?', correct_answer: 'Saint Paul', incorrect_answers: ['Minneapolis', 'Rochester', 'Duluth'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Missouri?', correct_answer: 'Jefferson City', incorrect_answers: ['Kansas City', 'Saint Louis', 'Springfield'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Colorado?', correct_answer: 'Denver', incorrect_answers: ['Colorado Springs', 'Aurora', 'Fort Collins'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Washington?', correct_answer: 'Olympia', incorrect_answers: ['Seattle', 'Spokane', 'Tacoma'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Oregon?', correct_answer: 'Salem', incorrect_answers: ['Portland', 'Eugene', 'Gresham'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Arizona?', correct_answer: 'Phoenix', incorrect_answers: ['Tucson', 'Mesa', 'Chandler'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Nevada?', correct_answer: 'Carson City', incorrect_answers: ['Las Vegas', 'Henderson', 'Reno'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Utah?', correct_answer: 'Salt Lake City', incorrect_answers: ['West Valley City', 'Provo', 'West Jordan'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of New Mexico?', correct_answer: 'Santa Fe', incorrect_answers: ['Albuquerque', 'Las Cruces', 'Rio Rancho'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Texas?', correct_answer: 'Austin', incorrect_answers: ['Houston', 'Dallas', 'San Antonio'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Oklahoma?', correct_answer: 'Oklahoma City', incorrect_answers: ['Tulsa', 'Norman', 'Broken Arrow'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Kansas?', correct_answer: 'Topeka', incorrect_answers: ['Wichita', 'Overland Park', 'Kansas City'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Nebraska?', correct_answer: 'Lincoln', incorrect_answers: ['Omaha', 'Bellevue', 'Grand Island'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of South Dakota?', correct_answer: 'Pierre', incorrect_answers: ['Sioux Falls', 'Rapid City', 'Aberdeen'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of North Dakota?', correct_answer: 'Bismarck', incorrect_answers: ['Fargo', 'Grand Forks', 'Minot'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Montana?', correct_answer: 'Helena', incorrect_answers: ['Billings', 'Missoula', 'Great Falls'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Wyoming?', correct_answer: 'Cheyenne', incorrect_answers: ['Casper', 'Laramie', 'Gillette'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Idaho?', correct_answer: 'Boise', incorrect_answers: ['Nampa', 'Meridian', 'Idaho Falls'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the capital of Alaska?', correct_answer: 'Juneau', incorrect_answers: ['Anchorage', 'Fairbanks', 'Sitka'])

TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 branches of government?', correct_answer: 'Executive, Legislative, Judicial', incorrect_answers: ['Executive, Legislative, Military', 'Executive, Legislative, Police', 'Executive, Legislative, Fire Department'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 primary colors?', correct_answer: 'Red, Yellow, Blue', incorrect_answers: ['Red, Yellow, Green', 'Red, Blue, Green', 'Red, Blue, Yellow'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 states of matter?', correct_answer: 'Solid, Liquid, Gas', incorrect_answers: ['Solid, Liquid, Plasma', 'Solid, Liquid, Bose-Einstein Condensate', 'Solid, Liquid, Superfluid'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 parts of an atom?', correct_answer: 'Proton, Neutron, Electron', incorrect_answers: ['Proton, Neutron, Photon', 'Proton, Neutron, Quark', 'Proton, Neutron, Lepton'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 types of rock?', correct_answer: 'Igneous, Sedimentary, Metamorphic', incorrect_answers: ['Igneous, Sedimentary, Volcanic', 'Igneous, Sedimentary, Lava', 'Igneous, Sedimentary, Magma'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 types of clouds?', correct_answer: 'Cirrus, Cumulus, Stratus', incorrect_answers: ['Cirrus, Cumulus, Nimbus', 'Cirrus, Cumulus, Altostratus', 'Cirrus, Cumulus, Alto Cumulus'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 types of blood vessels?', correct_answer: 'Arteries, Veins, Capillaries', incorrect_answers: ['Arteries, Veins, Arterioles', 'Arteries, Veins, Venules', 'Arteries, Veins, Arteriovenous'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Choose the one that is not a bone: Femur, Humerus, Radius', correct_answer: 'Radius', incorrect_answers: ['Femur', 'Humerus', 'Tibia'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 types of muscle?', correct_answer: 'Skeletal, Cardiac, Smooth', incorrect_answers: ['Skeletal, Cardiac, Striated', 'Skeletal, Cardiac, Voluntary', 'Skeletal, Cardiac, Involuntary'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which planet is the 3rd from the sun?', correct_answer: 'Earth', incorrect_answers: ['Mars', 'Venus', 'Mercury'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 primary colors of light?', correct_answer: 'Red, Green, Blue', incorrect_answers: ['Red, Green, Yellow', 'Red, Blue, Green', 'Red, Blue, Yellow'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What are the 3 types of heat transfer?', correct_answer: 'Conduction, Convection, Radiation', incorrect_answers: ['Conduction, Convection, Evaporation', 'Conduction, Convection, Sublimation', 'Conduction, Convection, Condensation'])

TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who was the first president of the United States?', correct_answer: 'George Washington', incorrect_answers: ['John Adams', 'Thomas Jefferson', 'James Madison'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who was the first person to walk on the moon?', correct_answer: 'Neil Armstrong', incorrect_answers: ['Buzz Aldrin', 'Michael Collins', 'Yuri Gagarin'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who was the first person to invent the light bulb?', correct_answer: 'Thomas Edison', incorrect_answers: ['Nikola Tesla', 'Benjamin Franklin', 'Alexander Graham Bell'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who was the first person to invent the telephone?', correct_answer: 'Alexander Graham Bell', incorrect_answers: ['Thomas Edison', 'Nikola Tesla', 'Benjamin Franklin'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who was the first person to invent the airplane?', correct_answer: 'Orville and Wilbur Wright', incorrect_answers: ['Alberto Santos-Dumont', 'Gustave Whitehead', 'Richard Pearse'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who was the first person to invent the computer?', correct_answer: 'Charles Babbage', incorrect_answers: ['Alan Turing', 'Ada Lovelace', 'John von Neumann'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who was the first person to invent the internet?', correct_answer: 'Tim Berners-Lee', incorrect_answers: ['Vint Cerf', 'Robert Kahn', 'Larry Roberts'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who has the most home runs in MLB history?', correct_answer: 'Barry Bonds', incorrect_answers: ['Hank Aaron', 'Babe Ruth', 'Alex Rodriguez'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who has the most points in NBA history?', correct_answer: 'Kareem Abdul-Jabbar', incorrect_answers: ['Karl Malone', 'LeBron James', 'Kobe Bryant'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who has the most goals in NHL history?', correct_answer: 'Wayne Gretzky', incorrect_answers: ['Gordie Howe', 'Jaromir Jagr', 'Brett Hull'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who has the most goals in FIFA World Cup history?', correct_answer: 'Marta', incorrect_answers: ['Miroslav Klose', 'Ronaldo', 'Pelé'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Who has the most points in NFL history?', correct_answer: 'Jerry Rice', incorrect_answers: ['Emmitt Smith', 'LaDainian Tomlinson', 'Randy Moss'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many continents are there?', correct_answer: '7', incorrect_answers: ['6', '5', '4'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many oceans are there?', correct_answer: '5', incorrect_answers: ['4', '3', '2'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many planets are there in our solar system?', correct_answer: '8', incorrect_answers: ['9', '7', '6'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many bones are in the human body?', correct_answer: '206', incorrect_answers: ['208', '204', '202'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many teeth does an adult human have?', correct_answer: '32', incorrect_answers: ['30', '28', '26'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many feet are in a mile?', correct_answer: '5280', incorrect_answers: ['5000', '5500', '6000'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many yards are in a mile?', correct_answer: '1760', incorrect_answers: ['1500', '2000', '2500'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many feet are in a yard?', correct_answer: '3', incorrect_answers: ['2', '4', '5'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many inches are in a foot?', correct_answer: '12', incorrect_answers: ['10', '14', '16'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many ounces are in a pound?', correct_answer: '16', incorrect_answers: ['12', '14', '18'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many pounds are in a ton?', correct_answer: '2000', incorrect_answers: ['1000', '1500', '2500'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many quarts are in a gallon?', correct_answer: '4', incorrect_answers: ['3', '5', '6'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many pints are in a quart?', correct_answer: '2', incorrect_answers: ['1', '3', '4'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many cups are in a pint?', correct_answer: '2', incorrect_answers: ['1', '3', '4'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many tablespoons are in a cup?', correct_answer: '16', incorrect_answers: ['12', '14', '18'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many teaspoons are in a tablespoon?', correct_answer: '3', incorrect_answers: ['2', '4', '5'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many days are in a year?', correct_answer: '365', incorrect_answers: ['364', '366', '367'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many days are in a leap year?', correct_answer: '366', incorrect_answers: ['365', '364', '367'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many weeks are in a year?', correct_answer: '52', incorrect_answers: ['51', '53', '54'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many months are in a year?', correct_answer: '12', incorrect_answers: ['11', '13', '14'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many hours are in a day?', correct_answer: '24', incorrect_answers: ['23', '25', '26'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many minutes are in an hour?', correct_answer: '60', incorrect_answers: ['59', '61', '62'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many seconds are in a minute?', correct_answer: '60', incorrect_answers: ['59', '61', '62'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many seconds are in an hour?', correct_answer: '3600', incorrect_answers: ['3500', '3700', '3800'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest ocean?', correct_answer: 'Pacific', incorrect_answers: ['Atlantic', 'Indian', 'Arctic'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the smallest ocean?', correct_answer: 'Arctic', incorrect_answers: ['Pacific', 'Atlantic', 'Indian'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest continent?', correct_answer: 'Asia', incorrect_answers: ['Africa', 'North America', 'South America'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the smallest continent?', correct_answer: 'Australia', incorrect_answers: ['Europe', 'Antarctica', 'Africa'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest country by land area?', correct_answer: 'Russia', incorrect_answers: ['Canada', 'China', 'United States'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the smallest country by land area?', correct_answer: 'Vatican City', incorrect_answers: ['Monaco', 'Nauru', 'Tuvalu'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest country by population?', correct_answer: 'China', incorrect_answers: ['India', 'United States', 'Indonesia'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the smallest country by population?', correct_answer: 'Vatican City', incorrect_answers: ['Tuvalu', 'Nauru', 'Palau'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the tallest mountain?', correct_answer: 'Mount Everest', incorrect_answers: ['K2', 'Kang', 'Lhotse'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the longest river?', correct_answer: 'Nile', incorrect_answers: ['Amazon', 'Mississippi', 'Yangtze'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest lake?', correct_answer: 'Caspian Sea', incorrect_answers: ['Lake Superior', 'Lake Victoria', 'Lake Huron'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest desert?', correct_answer: 'Antarctica', incorrect_answers: ['Sahara', 'Arabian', 'Gobi'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest island?', correct_answer: 'Greenland', incorrect_answers: ['New Guinea', 'Borneo', 'Madagascar'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest forest?', correct_answer: 'Amazon', incorrect_answers: ['Congo', 'Valdivian', 'Taiga'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest waterfall?', correct_answer: 'Angel', incorrect_answers: ['Victoria', 'Niagara', 'Iguazu'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest canyon?', correct_answer: 'Grand', incorrect_answers: ['Fish River', 'Yarlung Tsangpo', 'Tara'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest cave?', correct_answer: 'Son Doong', incorrect_answers: ['Deer', 'Clearwater', 'Sarawak'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest volcano?', correct_answer: 'Mauna Loa', incorrect_answers: ['Mauna Kea', 'Mount Everest', 'Mount Kilimanjaro'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest glacier?', correct_answer: 'Polar', incorrect_answers: ['Lambert', 'Baltoro', 'Siachen'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest reef?', correct_answer: 'Great Barrier', incorrect_answers: ['Belize Barrier', 'Palancar', 'Tubbataha'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest delta?', correct_answer: 'Ganges', incorrect_answers: ['Niger', 'Mekong', 'Nile'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest gulf?', correct_answer: 'Mexico', incorrect_answers: ['Persian', 'California', 'Finland'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest bay?', correct_answer: 'Hudson', incorrect_answers: ['James', 'Chesapeake', 'Tampa'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest strait?', correct_answer: 'Bering', incorrect_answers: ['Gibraltar', 'Bosporus', 'Malacca'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest canal?', correct_answer: 'Panama', incorrect_answers: ['Suez', 'Kiel', 'Erie'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest mountain range?', correct_answer: 'Himalayas', incorrect_answers: ['Andes', 'Rockies', 'Alps'])

TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest animal?', correct_answer: 'Blue Whale', incorrect_answers: ['African Elephant', 'Giraffe', 'Saltwater Crocodile'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest bird?', correct_answer: 'Ostrich', incorrect_answers: ['Emu', 'Cassowary', 'Rhea'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest fish?', correct_answer: 'Whale Shark', incorrect_answers: ['Basking Shark', 'Great White Shark', 'Tiger Shark'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest reptile?', correct_answer: 'Saltwater Crocodile', incorrect_answers: ['Nile Crocodile', 'American Alligator', 'Gharial'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest amphibian?', correct_answer: 'Chinese Giant Salamander', incorrect_answers: ['Japanese Giant Salamander', 'Hellbender', 'Giant Barred Frog'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest insect?', correct_answer: 'Goliath Beetle', incorrect_answers: ['Titan Beetle', 'Atlas Moth', 'Hercules Beetle'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest spider?', correct_answer: 'Goliath Birdeater', incorrect_answers: ['Huntsman', 'Tarantula', 'Wolf Spider'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest land animal?', correct_answer: 'African Elephant', incorrect_answers: ['Asian Elephant', 'White Rhinoceros', 'Hippopotamus'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest cat?', correct_answer: 'Siberian Tiger', incorrect_answers: ['Bengal Tiger', 'African Lion', 'Jaguar'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest dog?', correct_answer: 'Great Dane', incorrect_answers: ['Irish Wolfhound', 'Saint Bernard', 'Newfoundland'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest bear?', correct_answer: 'Kodiak Bear', incorrect_answers: ['Polar Bear', 'Brown Bear', 'Grizzly Bear'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest rodent?', correct_answer: 'Capybara', incorrect_answers: ['Beaver', 'Porcupine', 'Nutria'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest primate?', correct_answer: 'Gorilla', incorrect_answers: ['Orangutan', 'Chimpanzee', 'Bonobo'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest snake?', correct_answer: 'Green Anaconda', incorrect_answers: ['Reticulated Python', 'Indian Python', 'Burmese Python'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest turtle?', correct_answer: 'Leatherback Sea Turtle', incorrect_answers: ['Green Sea Turtle', 'Loggerhead Sea Turtle', 'Hawksbill Sea Turtle'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest tortoise?', correct_answer: 'Galápagos Tortoise', incorrect_answers: ['Aldabra Giant Tortoise', 'African Spurred Tortoise', 'Sulcata Tortoise'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is the largest penguin?', correct_answer: 'Emperor Penguin', incorrect_answers: ['King Penguin', 'Gentoo Penguin', 'Adélie Penguin'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which plant is poisonous to touch?', correct_answer: 'Poison Ivy', incorrect_answers: ['Poison Oak', 'Poison Sumac', 'Stinging Nettle'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which plant is poisonous to eat?', correct_answer: 'Deadly Nightshade', incorrect_answers: ['Castor Bean', 'Rosary Pea', 'Oleander'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which plant is poisonous to smell?', correct_answer: 'White Snakeroot', incorrect_answers: ['Lily of the Valley', 'Nerium Oleander', 'Foxglove'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a variable?', correct_answer: 'A symbol for a number we don\'t know yet', incorrect_answers: ['A number we know', 'A number we don\'t know', 'A symbol for a number we know'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a constant?', correct_answer: 'A number we know and don\'t change', incorrect_answers: ['A number we know and change', 'A number we don\'t know and change', 'A number we don\'t know and don\'t change'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What does mutable mean?', correct_answer: 'Can change', incorrect_answers: ['Can\'t change', 'Can change and can\'t change', 'Can\'t change and can change'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What does immutable mean?', correct_answer: 'Can\'t change', incorrect_answers: ['Can change', 'Can change and can\'t change', 'Can\'t change and can change'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a string?', correct_answer: 'A sequence of characters', incorrect_answers: ['A sequence of numbers', 'A sequence of symbols', 'A sequence of letters'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is an integer?', correct_answer: 'A whole number', incorrect_answers: ['A fraction', 'A decimal', 'A negative number'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a float?', correct_answer: 'A decimal number', incorrect_answers: ['A whole number', 'A fraction', 'A negative number'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a boolean?', correct_answer: 'True or False', incorrect_answers: ['Yes or No', '1 or 0', 'On or Off'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is an IP address?', correct_answer: 'A unique string of numbers separated by periods', incorrect_answers: ['A unique string of letters separated by periods', 'A unique string of symbols separated by periods', 'A unique string of characters separated by periods'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a URL?', correct_answer: 'A web address', incorrect_answers: ['A web page', 'A web site', 'A web server'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a domain name?', correct_answer: 'A unique name that identifies a website', incorrect_answers: ['A unique name that identifies a web page', 'A unique name that identifies a web site', 'A unique name that identifies a web server'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a web server?', correct_answer: 'A computer that stores and serves web pages', incorrect_answers: ['A computer that stores and serves web sites', 'A computer that stores and serves web addresses', 'A computer that stores and serves web domains'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a web page?', correct_answer: 'A document on the World Wide Web', incorrect_answers: ['A document on the World Wide Site', 'A document on the World Wide Address', 'A document on the World Wide Domain'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a web site?', correct_answer: 'A collection of web pages', incorrect_answers: ['A collection of web addresses', 'A collection of web domains', 'A collection of web servers'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'What is a web browser?', correct_answer: 'A software application for accessing information on the World Wide Web', incorrect_answers: ['A software application for accessing information on the World Wide Site', 'A software application for accessing information on the World Wide Address', 'A software application for accessing information on the World Wide Domain'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the fastest?', correct_answer: 'Peregrine Falcon', incorrect_answers: ['Cheetah', 'Pronghorn', 'Sailfish'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the slowest?', correct_answer: 'Sloth', incorrect_answers: ['Garden Snail', 'Starfish', 'Sea Cucumber'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the heaviest?', correct_answer: 'Blue Whale', incorrect_answers: ['African Elephant', 'Giraffe', 'Saltwater Crocodile'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the lightest?', correct_answer: 'Bee Hummingbird', incorrect_answers: ['Etruscan Shrew', 'Kitti\'s Hog-nosed Bat', 'Bumblebee Bat'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the tallest?', correct_answer: 'Giraffe', incorrect_answers: ['African Elephant', 'Saltwater Crocodile', 'Ostrich'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the shortest?', correct_answer: 'Etruscan Shrew', incorrect_answers: ['Kitti\'s Hog-nosed Bat', 'Bee Hummingbird', 'Bumblebee Bat'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the loudest?', correct_answer: 'Blue Whale', incorrect_answers: ['Elephant', 'Howler Monkey', 'Lion'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the quietest?', correct_answer: 'Owl', incorrect_answers: ['Deer', 'Rabbit', 'Fox'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the smartest?', correct_answer: 'Dolphin', incorrect_answers: ['Elephant', 'Chimpanzee', 'Orangutan'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which animal is the most venomous?', correct_answer: 'Inland Taipan', incorrect_answers: ['Box Jellyfish', 'Blue-ringed Octopus', 'Cone Snail'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many senators are there in the United States?', correct_answer: '100', incorrect_answers: ['50', '200', '300'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many representatives are there in the United States?', correct_answer: '435', incorrect_answers: ['100', '200', '300'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many justices are there in the United States Supreme Court?', correct_answer: '9', incorrect_answers: ['5', '7', '11'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many amendments are there in the United States Constitution?', correct_answer: '27', incorrect_answers: ['10', '20', '30'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How many states are there in the United States?', correct_answer: '50', incorrect_answers: ['48', '52', '54'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How long is a term for a United States senator?', correct_answer: '6 years', incorrect_answers: ['2 years', '4 years', '8 years'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How long is a term for a United States representative?', correct_answer: '2 years', incorrect_answers: ['4 years', '6 years', '8 years'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How long is a term for the President of the United States?', correct_answer: '4 years', incorrect_answers: ['2 years', '6 years', '8 years'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How long is a term for a United States Supreme Court justice?', correct_answer: 'Life', incorrect_answers: ['10 years', '20 years', '30 years'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How long is a term for a United States governor?', correct_answer: '4 years', incorrect_answers: ['2 years', '6 years', '8 years'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'How long is a term for a United States mayor?', correct_answer: '4 years', incorrect_answers: ['2 years', '6 years', '8 years'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest city in the United States?', correct_answer: 'New York City', incorrect_answers: ['Los Angeles', 'Chicago', 'Houston'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the smallest city in the United States?', correct_answer: 'Buford', incorrect_answers: ['Vernon', 'Monowi', 'Lost Springs'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest state in the United States?', correct_answer: 'Alaska', incorrect_answers: ['Texas', 'California', 'Montana'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the smallest state in the United States?', correct_answer: 'Rhode Island', incorrect_answers: ['Delaware', 'Connecticut', 'New Jersey'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest county in the United States?', correct_answer: 'San Bernardino', incorrect_answers: ['Coconino', 'Nye', 'Maricopa'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the smallest county in the United States?', correct_answer: 'Kalawao', incorrect_answers: ['New York', 'San Francisco', 'Philadelphia'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest university in the United States?', correct_answer: 'Liberty', incorrect_answers: ['Arizona State', 'Central Florida', 'Texas A&M'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the smallest university in the United States?', correct_answer: 'Alaska Bible', incorrect_answers: ['Berea', 'Haskell Indian Nations', 'Oglala Lakota'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest library in the United States?', correct_answer: 'Library of Congress', incorrect_answers: ['New York Public Library', 'Boston Public Library', 'Chicago Public Library'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest museum in the United States?', correct_answer: 'Metropolitan Museum of Art', incorrect_answers: ['Smithsonian', 'Art Institute of Chicago', 'Museum of Fine Arts, Boston'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest zoo in the United States?', correct_answer: 'Bronx Zoo', incorrect_answers: ['San Diego Zoo', 'Columbus Zoo', 'Fort Worth Zoo'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest park in the United States?', correct_answer: 'Wrangell-St. Elias', incorrect_answers: ['Gates of the Arctic', 'Denali', 'Katmai'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest forest in the United States?', correct_answer: 'Tongass', incorrect_answers: ['Chugach', 'Humboldt-Toiyabe', 'Salmon-Challis'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest mountain in the United States?', correct_answer: 'Denali', incorrect_answers: ['Mount Saint Elias', 'Mount Foraker', 'Mount Bona'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest river in the United States?', correct_answer: 'Mississippi', incorrect_answers: ['Missouri', 'Yukon', 'Rio Grande'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest lake in the United States?', correct_answer: 'Lake Superior', incorrect_answers: ['Lake Michigan', 'Lake Huron', 'Lake Erie'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest island in the United States?', correct_answer: 'Hawaii', incorrect_answers: ['Kodiak', 'Puerto Rico', 'Prince of Wales'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest desert in the United States?', correct_answer: 'Great Basin', incorrect_answers: ['Mojave', 'Chihuahuan', 'Sonoran'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest canyon in the United States?', correct_answer: 'Grand', incorrect_answers: ['Fish River', 'Yarlung Tsangpo', 'Tara'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest cave in the United States?', correct_answer: 'Mammoth', incorrect_answers: ['Lechuguilla', 'Jewel', 'Wind'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest volcano in the United States?', correct_answer: 'Mauna Loa', incorrect_answers: ['Mauna Kea', 'Mount Saint Helens', 'Mount Rainier'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest glacier in the United States?', correct_answer: 'Bering', incorrect_answers: ['Malaspina', 'Bagley', 'Taku'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which is the largest reef in the United States?', correct_answer: 'Florida', incorrect_answers: ['Hawaii', 'American Samoa', 'Guam'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a noun?', correct_answer: 'Car', incorrect_answers: ['Run', 'Fast', 'Jump'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a verb?', correct_answer: 'Run', incorrect_answers: ['Car', 'Fast', 'Jump'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is an adjective?', correct_answer: 'Fast', incorrect_answers: ['Car', 'Run', 'Jump'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is an adverb?', correct_answer: 'Quickly', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a pronoun?', correct_answer: 'He', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a preposition?', correct_answer: 'Under', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a conjunction?', correct_answer: 'And', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is an interjection?', correct_answer: 'Wow', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a determiner?', correct_answer: 'The', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a quantifier?', correct_answer: 'Some', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a compound noun?', correct_answer: 'Toothpaste', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a proper noun?', correct_answer: 'New York', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'easy', content: 'Which of these is a common noun?', correct_answer: 'City', incorrect_answers: ['Car', 'Run', 'Fast'])
TriviaQuestion.find_or_create_by(difficulty: 'medium', content: 'Which is a palindrome?', correct_answer: 'Racecar', incorrect_answers: ['Dog', 'Enter', 'Mississippi'])

TriviaQuestion.find_or_create_by(difficulty: 'medium', content: 'What is the name of George Washingtons wife?', correct_answer: 'Martha', incorrect_answers: ['Abigail', 'Dolley', 'Elizabeth'])
TriviaQuestion.find_or_create_by(difficulty: 'medium', content: 'What is the name of John Adams wife?', correct_answer: 'Abigail', incorrect_answers: ['Martha', 'Dolley', 'Elizabeth'])
